# Generated by Django 5.1.3 on 2024-11-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_alter_profiles_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='dni',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
