# Generated by Django 5.1.3 on 2024-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_profiles_dni_alter_profiles_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='dni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='foto_perfil',
            field=models.ImageField(default='users/no-photo.png', upload_to='users/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
