# Generated by Django 5.1.3 on 2024-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_alter_profiles_dni_alter_profiles_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='dni',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
