# Generated by Django 5.1.3 on 2024-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_bankaccounts_saldo'),
        ('Profiles', '0006_alter_profiles_dni_alter_profiles_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='cuentas_favoritas',
            field=models.ManyToManyField(blank=True, null=True, to='Accounts.sendoraaccounts'),
        ),
    ]
