# Generated by Django 5.1.3 on 2024-11-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_bankaccounts_saldo'),
        ('Profiles', '0007_profiles_cuentas_favoritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='cuentas_favoritas',
            field=models.ManyToManyField(blank=True, to='Accounts.sendoraaccounts'),
        ),
    ]
