# Generated by Django 5.1.3 on 2024-11-14 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('alias', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('saldo', models.IntegerField()),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transacciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.transactions')),
            ],
        ),
    ]
