# Generated by Django 5.1.3 on 2024-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_accounts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='transacciones',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
