# Generated by Django 5.1.3 on 2024-11-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_accounts_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='alias',
            field=models.CharField(max_length=50),
        ),
    ]
