# Generated by Django 5.1.3 on 2024-11-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_accounts_bankaccounts_sendoraaccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccounts',
            options={'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Bancarias'},
        ),
        migrations.AlterModelOptions(
            name='sendoraaccounts',
            options={'verbose_name': 'Cuenta Sendora', 'verbose_name_plural': 'Sendora'},
        ),
    ]
