# Generated by Django 5.1.3 on 2024-11-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_bankaccounts_options_and_more'),
        ('Banks', '0002_alter_banks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Banks.banks'),
        ),
        migrations.AlterField(
            model_name='sendoraaccounts',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.bankaccounts'),
        ),
    ]
