# Generated by Django 5.1.3 on 2024-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_remove_sendoraaccounts_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=135329.71, max_digits=10),
        ),
    ]
