# Generated by Django 5.1.3 on 2024-11-20 16:36

import Apps.Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_bankaccounts_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Apps.Accounts.models.generar_saldo_aleatorio, max_digits=10),
        ),
    ]
