# Generated by Django 5.1.3 on 2024-11-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Motives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motives',
            options={'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
    ]
