# Generated by Django 5.1.3 on 2024-11-14 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('Alquileres', 'Alquileres'), ('Aportes de capital', 'Aportes de capital'), ('Bienes registrables habitualistas', 'Bienes registrables habitualistas'), ('Bienes registrables no habitualistas', 'Bienes registrables no habitualistas'), ('Cuota', 'Cuota'), ('Expensas', 'Expensas'), ('Factura', 'Factura'), ('Haberes', 'Haberes'), ('Honorarios', 'Honorarios'), ('Inmobiliaria habitualista', 'Inmobiliaria habitualista'), ('Inmobiliaria', 'Inmobiliaria'), ('Préstamos', 'Préstamos'), ('Seguros', 'Seguros'), ('Suscripción a obligaciones negociables', 'Suscripción a obligaciones negociables'), ('Varios', 'Varios')], max_length=50)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaciones_como_destinatario', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaciones_como_remitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
