# Generated by Django 5.1.3 on 2024-11-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_reasons_transactions_tipo_alter_transactions_motivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasons',
            options={'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transacion', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
