# Generated by Django 5.1.3 on 2024-11-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motives', '0001_initial'),
        ('Transactions', '0003_alter_reasons_options_alter_transactions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Motives.motives'),
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Reasons',
        ),
    ]
