# Generated by Django 5.1.3 on 2024-11-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Motives', '0001_initial'),
        ('Transactions', '0004_alter_transactions_motivo_remove_transactions_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Motives.motives'),
        ),
    ]
