# Generated by Django 5.1.3 on 2024-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dni',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
