# Generated by Django 5.1.3 on 2024-11-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
    ]
