# Generated by Django 5.1.3 on 2024-11-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_accounts_bankaccounts_sendoraaccounts'),
        ('Income', '0002_rename_remitente_incomes_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.sendoraaccounts'),
        ),
    ]
