# Generated by Django 5.1.3 on 2024-11-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_remove_sendoraaccounts_banco'),
        ('Income', '0004_alter_incomes_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.corporateaccounts'),
        ),
    ]
