# Generated by Django 5.1.3 on 2024-11-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Income', '0006_alter_incomes_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='fecha',
            new_name='fecha_y_hora',
        ),
    ]
