# Generated by Django 5.1.3 on 2024-11-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_bankaccounts_saldo'),
        ('Income', '0007_rename_fecha_incomes_fecha_y_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.sendoraaccounts'),
        ),
    ]
